### ISSUE TITLE
Any plan to support google chrome?

### ISSUE THREAD

**Issue by coo11** [tumuyan/Tree-Style-History#1]
This plugin looks useful.

**Comment by tumuyan** [comment]
It support Google Chrome, Microsoft Edge, and others Chromium browsers.
Cause of upload to chrome webstore needs a developer account, which requires credit card payment, so I not upload to chrome webstore yet.
But you can install it in Chrome develop mode, refer:

0. download the  file and  unzip it to somewhere  https://github.com/tumuyan/Tree-Style-History/archive/refs/heads/main.zip  
1. Open the Extension Management page by navigating to chrome://extensions.
2. The Extension Management page can also be opened by clicking on the Chrome menu, hovering over More Tools then selecting Extensions.
3. Enable Developer Mode by clicking the toggle switch next to Developer mode.

![image](https://user-images.githubusercontent.com/3126801/116433382-05b39b80-a87c-11eb-85c3-ff9816aceddb.png)

4. Click the LOAD UNPACKED button and select the extension directory .
![image](https://user-images.githubusercontent.com/3126801/116433908-84a8d400-a87c-11eb-8948-7add7c1a282f.png)

5. Load Extension

**Comment by coo11** [comment]
Solved. Very thankful!

**Comment by oXnMe** [comment]
Now you can get it on Chrome Web Store
[https://chrome.google.com/webstore/detail/tree-style-history/khcenbpnhbeplojhaolbpldmoppicold](https://chrome.google.com/webstore/detail/tree-style-history/khcenbpnhbeplojhaolbpldmoppicold)
