### ISSUE TITLE
Feature Request: Toggle on/off "search history at this site" right-click menu entry

### ISSUE THREAD

**Issue by Bamajon1974** [tumuyan/Tree-Style-History#15]
Please add the ability to toggle on or off the "search history at this site" right-click menu entry. Also, when enabling the right-click menu entry, please change text for first letters to display in capitals to match the style of other right-click menu entries in the browser. 

Thanks!

**Comment by tumuyan** [comment]
Thanks , I will add a option and fix the text this weekend.

**Comment by Bamajon1974** [comment]
Great! Thank you! Please give me a head's up when you submit the new extension to the Chrome store.

**Comment by tumuyan** [comment]
it has been upgrade in Chrome store. and it will need some days for edge store approve

**Comment by Bamajon1974** [comment]
Thank you very much!
