### ISSUE TITLE
为树状历史中的filter添加说明

### ISSUE THREAD

**Issue by yoghurtdewdew** [tumuyan/Tree-Style-History#19]
你好，这个filter里的这些图标，不是很懂什么意思，可以添加一个说明吗？

<img width="241" alt="image" src="https://github.com/tumuyan/Tree-Style-History/assets/63794438/8cf09e41-8b1e-4aed-8d40-4405ca9b7ec7">

**Comment by tumuyan** [comment]
https://github.com/tumuyan/Tree-Style-History/issues/9

**Comment by yoghurtdewdew** [comment]
感谢您的提示！谢谢！

**Comment by yoghurtdewdew** [comment]
你好！发现现在比之前多了一个 🧭 ，是什么意思呢？

**Comment by tumuyan** [comment]
没记错的话应该是从历史中打开的新页面
