### ISSUE TITLE
Overwrite Default History Interface

### ISSUE THREAD

**Issue by coo11** [tumuyan/Tree-Style-History#4]
Hello, thanks for your awesome work. This extension helps me a lot.
But it doesn't overwrite the default history interface in recent version by default on Chrome.
Could you provide a switch to determine whether to override the default history interface?

**Comment by tumuyan** [comment]
You could set shortcuts in  [chrome://extensions/shortcuts](chrome://extensions/shortcuts) and set `Ctrl+h` for tree style history, 

The option page of Tree style history also link to the shortcuts setting page.

![IMG_20210622_093156](https://user-images.githubusercontent.com/3126801/122848920-1264e500-d33d-11eb-8ca2-e9b795450d63.jpg)

**Comment by Geeyun-JY3** [comment]
Setting shortcuts in chrome://extensions/shortcuts is not enough. What if I open the history through mouse click?

**Comment by tumuyan** [comment]
> Setting shortcuts in chrome://extensions/shortcuts is not enough. What if I open the history through mouse click?

there also have a option for mouse click.
when the option is select as blow, you could open the tree style history by click  "more" in the popup page.

![IMG_20210629_224322.jpg](https://user-images.githubusercontent.com/3126801/123818635-bc3f0580-d92b-11eb-941b-891648daf185.jpg)

**Comment by Geeyun-JY3** [comment]
> > Setting shortcuts in chrome://extensions/shortcuts is not enough. What if I open the history through mouse click?
> 
> there also have a option for mouse click.
> when the option is select as blow, you could open the tree style history by click "more" in the popup page.
> 
> ![IMG_20210629_224322.jpg](https://user-images.githubusercontent.com/3126801/123818635-bc3f0580-d92b-11eb-941b-891648daf185.jpg)

I mean open the history by clicking the button in Chrome menu 
![image](https://user-images.githubusercontent.com/49396421/123820395-2310ee80-d92d-11eb-9709-260b42b3926a.png)

**Comment by tumuyan** [comment]
> I mean open the history by clicking the button in Chrome menu

(I'm using Edge browser.) An extension in Edge can only override Edge's own history page, or not,  cannot be toggled through options. Considering that users sometimes need to visit the browser's own history page, I don't override it.
If you still use the bookmarks bar (which is not popular anymore), you can add the pages of tree style history as bookmarks and place it to the bookmarks bar.

**Comment by Geeyun-JY3** [comment]
> (I'm using Edge browser.) An extension in Edge can only override Edge's own history page, or not, cannot be toggled through options. Considering that users sometimes need to visit the browser's own history page, I don't override it.
> If you still use the bookmarks bar (which is not popular anymore), you can add the pages of tree style history as bookmarks and place it to the bookmarks bar.

I see.

**Comment by Geeyun-JY3** [comment]
Just confused. Recent History on which Tree Style History is based has a option that override the default history page.
![image](https://user-images.githubusercontent.com/49396421/123943708-01684380-d9cf-11eb-8703-0b4305107851.png)

Why Tree Style History cannot has this option?

**Comment by tumuyan** [comment]
> Just confused. Recent History on which Tree Style History is based has a option that override the default history page.
> ![image](https://user-images.githubusercontent.com/49396421/123943708-01684380-d9cf-11eb-8703-0b4305107851.png)
> 
> Why Tree Style History cannot has this option?

This feature does not work in edge. To avoid such problems for users, this option has been removed.

**Comment by Geeyun-JY3** [comment]
> This feature does not work in edge. To avoid such problems for users, this option has been removed.

Sad😑

**Comment by tumuyan** [comment]
3.1.8 update a new function, now you could open the tree style history page by click the icon.  
This is just a new way to open TSH and still doesn't override the browser's own history page
![1629374845740](https://user-images.githubusercontent.com/3126801/130065869-09bbd17c-6aab-4e74-aa88-5d98c9b93abe.jpg)
