### ISSUE TITLE
没法正确地打开树状历史

### ISSUE THREAD

**Issue by H4M5TER** [tumuyan/Tree-Style-History#6]
在点击扩展按钮显示的界面中，点击“更多”按钮，预期是打开树状历史（或者至少是线性历史，最好是可配置的），但是实际上只会打开`edge://history`。
扩展版本 3.1.7，Edge 版本 92.0.902.62。

**Comment by H4M5TER** [comment]
仍然可以通过点击旁边的齿轮（设置）按钮来打开这个扩展提供的页面，但是就要多走一步了。
实际上我今天检查了一下发现有提供快捷键，所以其实也没有很强烈的需求。

**Comment by tumuyan** [comment]
> 仍然可以通过点击旁边的齿轮（设置）按钮来打开这个扩展提供的页面，但是就要多走一步了。
> 实际上我今天检查了一下发现有提供快捷键，所以其实也没有很强烈的需求。

已经收到了许多类似的反馈了，计划增加一个选项，配置是否使用popup页，如果否，则点击扩展图标、激活扩展的快捷键，全部指向树状历史

**Comment by tumuyan** [comment]
花了点时间增加了这个开关。已经上传edge商店，预计下周一审核结束。

**Comment by H4M5TER** [comment]
啊，我的意思其实是，在 popup 页点击‘更多’按钮，也没法正确的打开页面，而是会跳转到普通的历史记录页。
不过如果能点击扩展按钮直接打开树状历史，确实是最好的。
