### ISSUE TITLE
希望增加一个去除读取收藏夹数据的开关，或者增加一个移除收藏夹相关功能的分支

### ISSUE THREAD

**Issue by hjm7** [tumuyan/Tree-Style-History#7]
因为个人觉得收藏夹数据较为敏感，一个小提议希望考虑

**Comment by tumuyan** [comment]
1. 首先用户数据是完全脱机的，我觉得可以刨除这个顾虑？
2. 做一个开关意义不大，因为书签权限已经申请了，那么，用户数据有没有被扩展读取，用户是无法知晓的？
3. 做分支简单,麻烦的是需要再次上架…
