### ISSUE TITLE
右边日期下面的五个筛选  分别是啥意思

### ISSUE THREAD

**Issue by fodereas** [tumuyan/Tree-Style-History#9]
![image](https://user-images.githubusercontent.com/25607187/132839876-ba35b5b1-e4ea-48d9-b23f-af56cf6ae730.png)

鼠标放上去也没有提示   所以试了半天没搞懂这五个筛选是啥意思(*^▽^*)

**Comment by tumuyan** [comment]
你可以留意下左边的历史链接的末位，根据访问来源做了不同tag。 
这里的按钮是对来源的快速筛选。 
但是事实上用处不大，根据实际测试，浏览器提供的这个信息并不准确

**Comment by fodereas** [comment]
谢谢回复！末尾的图标我看到了  但不知道啥意思
感觉
第一个是链路打开历史
第二个是重复 （又好像不对）
第三个是only收藏的网站
第四、五 搞不懂

**Comment by tumuyan** [comment]
第二个是键盘输入，第三个是点击书签，第四是提交表单（比如登录、搜索可能是这一个分类），第五个是刷新

**Comment by fodereas** [comment]
感谢 这才懂了！
